import React, { useState } from 'react';
import {
  Button,
  Box,
  Container,
  FormField,
  Header,
  Input,
  Select,
  SpaceBetween,
  ColumnLayout,
  BreadcrumbGroup
} from '@cloudscape-design/components';

const CreateRunsheet = () => {
  const [orderIDs, setOrderIDs] = useState(['']); // Initial field
  const [riderName, setRiderName] = useState('');

  const handleOrderIDChange = (index, value) => {
    const newOrderIDs = [...orderIDs];
    newOrderIDs[index] = value;
    setOrderIDs(newOrderIDs);

    // Add new empty input field if the user presses Enter
    if (value.length > 5 && index === orderIDs.length - 1) {
      setOrderIDs([...newOrderIDs, '']);
    }
  };

  return (
    <Box>
        <SpaceBetween direction="vertical" size="m">
        <BreadcrumbGroup
          items={[
            { text: "Logistics", href: "/logistics" },
            { text: "Runsheet", href: "/runsheet" },
            { text: "Create RunSheet", href: "/runsheet/view" },
          ]}
          ariaLabel="Breadcrumbs"
        />
      <Container
        header={
          <Header variant="h1">
            Create Runsheet
          </Header>
        }
      >
        <SpaceBetween size="m">
        <ColumnLayout columns={2}>
          <FormField label="Runsheet No. (Generated by default)">
            <Input value="5425" readOnly disabled />
          </FormField>

          <FormField label="Select Rider Name">
            <Select
              selectedOption={riderName}
              onChange={({ detail }) => setRiderName(detail.selectedOption)}
              options={[
                { label: 'Santu', value: 'Santu' },
                { label: 'Other', value: 'Other' }
              ]}
              placeholder="Select Rider Name"
            />
          </FormField>
          </ColumnLayout>

          <Box textAlign="right">
            <Button variant="primary">Create a Runsheet</Button>
          </Box>
        </SpaceBetween>
      </Container>

      <Container header={<Header variant="h2">Line of orders</Header>}>
        <Box padding="s">
          <table style={{ width: '40%' }}>
            <thead>
              <tr>
                <th>S.no</th>
                <th>Order ID</th>
              </tr>
            </thead>
            <tbody >
              {orderIDs.map((orderID, index) => (
                <tr  key={index}>
                  <td style={{ textAlign: 'center' }}>{String(index + 1).padStart(2, '0')}</td>
                  <td >
                    <Input
                      value={orderID}
                      onChange={(e) => handleOrderIDChange(index, e.detail.value)}
                      placeholder="Enter Order ID"
                      ariaLabel={`Order ID ${index + 1}`}
                      autoFocus={index === orderIDs.length - 1}
                    />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </Box>
      </Container>
      </SpaceBetween>
    </Box>
  );
};

export default CreateRunsheet;
